name: Push Gem to Github Packages

on:
  push:
    branches: [ "an/update-dependencies" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1 # .ruby-version
      with:
          bundler-cache: true    # bundle install

    - name: Publish to GPR
      run: |
        mkdir -p ~/.gem
        touch ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > ~/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: shermanstravel